### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by Mikecoon** [react-native-community/react-native-text-input-mask#130]
Seems like nobody really cares about this project anymore.
Project is not compatible with react native 0.60.3 autolinking feature.

**Comment by kdawgwilk** [comment]
This is mostly due to lack of cocoapods support

**Comment by ivanzotov** [comment]
The module is not abandoned, but unfortunately I do not have much free time to actively support it (new maintainers are welcome), so autolinking feature is not supported yet.

**Comment by Mikecoon** [comment]
Turned out that 0.60+ doesn't compatible with swift, so there is no way to make it work.

Although, there are other options for masking text, but those plugins are worst.

**Comment by RageOfJustice** [comment]
So, may be make some workaround? Its unable to use this lib (RN 60.3) even when autlinking disabled (old way)

**Comment by Mikecoon** [comment]
> So, may be make some workaround? Its unable to use this lib (RN 60.3) even when autlinking disabled (old way)

Apparently, no. We have to rewrite module in Objective-C in order to make it work.

Sounds ridiculous to downgrade something from swift to obj-c in 2019...

**Comment by RageOfJustice** [comment]
I dont know swift or obj-c good enough but ive heard something about convert swift code into obj-c. Is it possible for InputMask lib?

**Comment by Mikecoon** [comment]
> I dont know swift or obj-c good enough but ive heard something about convert swift code into obj-c. Is it possible for InputMask lib?

Probably we can give it a shot, could you please provide us with details?..

**Comment by RyanThomas73** [comment]
@Mikecoon Can you clarify where you read / why you made this statement:

> Turned out that 0.60+ doesn't compatible with swift, so there is no way to make it work.
> 
> Although, there are other options for masking text, but those plugins are worst.

**Comment by betoharres** [comment]
Hi @Mikecoon do you have the source about RN 0.60 not being compatible with swift libraries? I can't find some official statement from the RN core team

**Comment by betoharres** [comment]
I don't think that swift  is the problem here, even though I'm a completely noob on this area I couldn't find a single statement about 0.60+ not being compatible with Swift. 

I saw that @kdawgwilk was able to achieve something in his fork, but I couldn't make it work on my machine. Here's his pod spec file in case someone needs it for a starting point:
```Ruby
Pod::Spec.new do |s|
  s.name          = "RNTextInputMask"
  s.version       = "1.0.1"
  s.source_files  = "ios/*.{h,m}", "ios/InputMask/InputMask/**/*.{h,swift}"
  s.ios.deployment_target = '8.0'
  s.tvos.deployment_target = '9.0'
  s.authors       = { "Gleb Mikheenko" => "glebmikheenk0o@gmail.com" }
  s.license       = "MIT"
  s.summary       = "Text input mask for React Native on iOS and Android."
  s.homepage      = "https://github.com/react-native-community/react-native-text-input-mask"
  s.source        = { :git => "https://github.com/glCoder8/react-native-text-input-mask.git" }

  s.dependency 'React'
end
```

He apparently made just a few changes to make it work: 
https://github.com/kdawgwilk/react-native-text-input-mask/commit/b809818bc255c552201dc9cfb30463e090f39771#diff-a9311b1bccf961f9e9432dfa679f05fa

https://github.com/kdawgwilk/react-native-text-input-mask/commit/2d1ec2125f0d72422dfc5c668bc8d4d7e2412d17

I hope this helps anyone that is trying to make this work. I tried yesterday and today, many different things but my lack of experience with swift/xcode/cocoapods just led me to nowhere

**Comment by kdawgwilk** [comment]
I am pretty sure the directory structure of the project changed and so my podspec is no longer valid with current versions, I also am no longer using this library since I creating my own wrapper around the InputMask libraries
