### ISSUE TITLE
Error while uploading to iTunesConnect for beta testing

### ISSUE THREAD

**Issue by ararog** [react-native-community/react-native-text-input-mask#22]
Here's the message while uploading to itunesconnect:

ERROR ITMS-90206: "Invalid Bundle. The bundle at 'myapp.app/Frameworks/InputMask.framework' contains disallowed file 'Frameworks'."

**Comment by ararog** [comment]
I found the problem, I set "Always Embed Swift Standard Libraries" to false on both RNTextInputMask and its InputMask dependency, now I can publish to Apple Store without a problem.

**Comment by lnikkila** [comment]
We’re also seeing this, the above works. “Always Embed Swift Standard Libraries” should be set on the app you’re publishing, not the library project. Additionally it should not be set on any app extensions you might have. More info about that error here, although CocoaPods specific: https://github.com/CocoaPods/CocoaPods/issues/4203

**Comment by Chleba** [comment]
Setting “Always Embed Swift Standard Libraries” isn't worked for me. I'm still unable to upload my App on Itunes Store.

**Comment by deehuey** [comment]
Thanks @lnikkila !

**Comment by aliemre** [comment]
Hi @lnikkila 

We have encountered same error. However, we could not manage to solve the issue with the way you suggest. Could you explain further? Thanks!

**Comment by lnikkila** [comment]
@aliemre 

See the screenshot below, make sure it’s the last build phase defined in your target. Also make sure “Always embed Swift standard libraries” is enabled in the target’s build settings, but not enabled on any libraries you have (except for InputMask which we’re working around with this script) or any app extension targets you may have.

<img width="854" alt="workaround" src="https://user-images.githubusercontent.com/1291143/34309951-615648a4-e75d-11e7-8e24-993a8bab58d8.png">

**Comment by MadGeorge** [comment]
The only question is why this is not in the Readme? I spent a hours to find the answer in google.

**Comment by Baskerville42** [comment]
I have the same issue. I have fixed it by adding New Run Script Phase into Building Phase(s) with the script  provided by @lnikkila 
Thank you very much!

**Comment by erhanbicer** [comment]
thank you @lnikkila . it's worked

**Comment by adrienthiery** [comment]
Hi there.
I've encountered that issue and I'm trying to fix it since yesterday.

I'm no iOS dev so I'm kind of struggling to get this one.

Even though I added the script, I still have the frameworks in the binary uploaded to AppStoreConnect.

I finally figured out that the script is trying to delete the wrong folder. It's trying to delete `~/Library/Developer/Xcode/DerivedData/MyApp-gcykowogazswsdfkqlcyslvyjgxa/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app/Frameworks/InputMask.framework/Frameworks` but this one does not exists and just after, I see warnings of "not copying" files:

```
[14:48:42]: ▸ Running script 'Fabric'
[14:48:42]: ▸ Copying ~/Library/Developer/Xcode/DerivedData/MyApp-gcykowogazswsdfkqlcyslvyjgxa/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/InputMask.framework/Frameworks/libswiftCoreImage.dylib
# And some more
```
which leaves me puzzled, as I thought that React Native bundling was all done in the `ios/build` folder.

In addition, the solution of changing the library is not gonna work for me, as I need all of that to run on our CI.

Any ideas, help, lead on how to go past that one?

How could I target the `IntermediateBuildFilesPath/UninstalledProducts/iphoneos/InputMask.framework/Frameworks` folder instead of the `BuildProductsPath/Release-iphoneos/MyApp.app/Frameworks/InputMask.framework/Frameworks` ?

Thanks a lot in advance.

(Using XCode `9.4`, RN `0.55.4` and `react-native-text-input-mask@0.8.0`, if that's any help)

**Comment by adrienthiery** [comment]
Small update here.

I finally managed to fix that on the CI.

A bit point that I might have missed was that `the build script needs to be the LAST one (after the *Embed frameworks* step)`.

Also, to disable the `Always embed swift standard libraries` to `false`, I created an npm script (in my `package.json`) : 
```
"fix-rn-text-input-mask": "sed -i '' -E 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO;/g' ./node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask.xcodeproj/project.pbxproj && sed -i '' -E 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO;/' ./node_modules/react-native-text-input-mask/ios/RNTextInputMask/InputMask/InputMask.xcodeproj/project.pbxproj",
```

That I run in the `postinstall` hook.

**Comment by lasersox** [comment]
Just ran into this today. The suggested fixes are not very good as they need to be re-applied every time we reinstall node_modules (something that happens *constantly* with react-native).

**Comment by cassianomon** [comment]
Documentation pull request: https://github.com/react-native-community/react-native-text-input-mask/pull/81

Fix pull request: https://github.com/react-native-community/react-native-text-input-mask/pull/99/commits

**Comment by cassianomon** [comment]
Hey @ivanzotov, should close the issue when the pull request gets merged.
