### ISSUE TITLE
undefined is not an object on Android

### ISSUE THREAD

**Issue by vinnichase** [react-native-community/react-native-text-input-mask#58]
Hi,

i don't get it running on Android. I'm using these package versions: 
```JSON
"react": "16.4.1",
"react-native": "0.55.4",
"react-native-text-input-mask": "0.7.0",
```
I'm working with typescript and used CRNA with `react-native-scripts-ts`.
and this input field:
```JSX
<TextInputMask
    mask={'[000],[00] m'}
    onChangeText={this.changeHeight}
    keyboardType="numeric" />
```
and i get this error on my smartphone screen:
```
undefined is not an object (evaluating '_reactNative.NativeModules.RNTextInputMask.mask')
```
this is the result of my link command:
```
$ react-native link react-native-text-input-mask
Scanning folders for symlinks in project-folder/node_modules (20ms)
$
```
Thanks for helping!

**Comment by vinnichase** [comment]
OK i found my mistake but i get still the same error. This closed issue https://github.com/react-native-community/react-native-text-input-mask/issues/27 seems to be the same. Since i was using CRNA it was not possible to link native modules. So I ejected from CRNA and successfully linked the package. And it is also added to MainApplication.java like @warlock27 writes it here https://github.com/react-native-community/react-native-text-input-mask/issues/27 but no success. I'm pretty frustrated, since it is a really simple use case and i already spent several hours on it.

**Comment by ivanzotov** [comment]
@vinnichase sorry for the delay, did you solve the problem? I will add documentation about manual linking soon, hope it will help – https://github.com/react-native-community/react-native-text-input-mask/issues/54#issuecomment-406718514

**Comment by vinnichase** [comment]
@ivanzotov no i postponed the input mask feature for my app, but i would still appreciate a robust solution for this.

**Comment by ivanzotov** [comment]
@vinnichase ok, so what steps should I do to reproduce the issue? As far as I understand: init new app with https://github.com/react-community/create-react-native-app and `react-native-scripts-ts` and try to build it on Android, right?

**Comment by vinnichase** [comment]
exactly, then you should run `yarn eject` and install your package and link.

**Comment by ivanzotov** [comment]
@vinnichase tried to reproduce steps with and without `react-native-scripts-ts`, it seems that it works good. What I did:

1. `create-react-native-app Masking`
2. `yarn eject`
3. `yarn add react-native-text-input-mask`
4. `react-native link react-native-text-input-mask`
5. Added some code (from readme) then build and run for Android

It's working. So I tried to use `react-native-scripts-ts` and did all steps but instead of first I run `create-react-native-app Masking --scripts-version=react-native-scripts-ts` and it also works good.

**Comment by ivanzotov** [comment]
Could you please try it with a new version of the library to reproduce the issue? And let me know if it still doesn't work to reopen the issue.

**Comment by vinnichase** [comment]
@ivanzotov ok thanks for investigating! since i excluded the package from my project i have to check it tomorrow. Let it closed for now and I will reopen it in case the error persists.

**Comment by andreyelek** [comment]
I have the same error in android though I made ejecting and linking
` react-native link react-native-text-input-mask
Scanning folders for symlinks in /home/elek/job/rn-public/node_modules (12ms)
rnpm-install info Linking react-native-text-input-mask android dependency
rnpm-install info Platform 'android' module react-native-text-input-mask has been successfully linked
`

**Comment by andreyelek** [comment]
@ivanzotov I have the same error in android though I made ejecting and linking
react-native link react-native-text-input-mask Scanning folders for symlinks in /home/elek/job/rn-public/node_modules (12ms) rnpm-install info Linking react-native-text-input-mask android dependency rnpm-install info Platform 'android' module react-native-text-input-mask has been successfully linked

Also maybe this issue is worth reopening

**Comment by faustoct** [comment]
I got this problem on ios, any idea how to solve it?

**Comment by brunoribeiro-lab** [comment]
up
